### ISSUE TITLE
Don`t work on Python 3.11

### ISSUE THREAD

**Issue by outdever** [yshestakov/ida_proc_1801#5]
After loading bin file  to IDA, got message:
PROCESSOR_ENTRY: D:\IDA Pro 8.3 (x86, x86_64)\procs\k1801vm1.py: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers (k1801vm1.py, line 1538)
Numbers written with a leading zero - is this the octal system you mean?

**Comment by yshestakov** [comment]
@outdever  thank you for your findings.
I have created a new branch & PR with fixes: https://github.com/yshestakov/ida_proc_1801/pull/7

**Comment by outdever** [comment]
it worked
